seed: 12345
canvas_size: [224, 224]
padding: 3
bg_color: "#7f7f7f"
colors: # Lists, so they can be sorted. Keys should be unique.
  - red: "#ff0000"
  - yellow: "#ffff00"
  - green: "#00ff00"
  - cyan: "#00ffff"
  - blue: "#0000ff"
  - magenta: "#ff00ff"
sizes:
  - small: 15  # NOTE: When using additional shapes, this is too small to discriminate them!
  - medium: 25
  - large: 32
shapes: # Lists, so they can be sorted. Keys should be unique. # NOTE: to correctly parse properties, the current bg.pl background knowledge assumes shapes have no _ character in them.
  - circle: { type: ellipse, n: 1, rot: 0 }
  - ellipsev: {type: ellipse, n: 2, rot: 90}
  - ellipseh: {type: ellipse, n: 2, rot: 0}
  - triangle: {type: polygon, n: 3, rot: 270}
  - downtriangle: {type: polygon, n: 3, rot: 90}
  - square: {type: polygon, n: 4, rot: 45}
  - diamond: {type: polygon, n: 4, rot: 0}
  #- pentagon: {type: polygon, n: 5, rot: 270}
  #- star_5: {type: star, n: 5, rot: 90}
  #- hexagon: {type: polygon, n: 6, rot: 0}
  #- star_6: {type: star, n: 6, rot: 0}
size_noise: 2
h_sigma: 0.01
s_sigma: 0.2
v_sigma: 0.2
background_knowledge: bg.pl
